version: '3.4'

services:
  desafio-mottu.api:
    image: ${DOCKER_REGISTRY-}desafioapi
    container_name: DesafioMottu.Api
    build:
      context: .
      dockerfile: src/DesafioMottu.Api/Dockerfile
    environment:
      - PUBSUB_EMULATOR_HOST=desafio-mottu-pubsub:8085
      - PUBSUB_PROJECT_ID=desafio-backend-mottu
    volumes:
      - ./.containers/app/Files/DriversLicenses:/app/Files/DriversLicenses
    depends_on:
      desafio-mottu-db:
        condition: service_healthy

  desafio-mottu-db:
    image: postgres:17.0
    container_name: DesafioMottu.Db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=desafiomottu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  desafio-mottu-seq:
    image: datalust/seq:2024.3
    container_name: DesafioMottu.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  desafio-mottu-redis:
    image: redis:7.4.0
    container_name: DesafioMottu.Redis
    restart: always
    ports:
      - '6379:6379'

  desafio-mottu-pubsub:
    image: google/cloud-sdk:494.0.0
    container_name: pubsub
    command: "gcloud beta emulators pubsub start --project=desafio-backend-mottu --host-port=0.0.0.0:8085"
    ports:
      - 8085:8085

  desafio-mottu-consumer:
    image: ${DOCKER_REGISTRY-}desafioconsumer
    container_name: DesafioMottu.Consumer
    build:
      context: .
      dockerfile: src/Functions/DesafioMottu.Consumer/Dockerfile
    environment:
      - PUBSUB_EMULATOR_HOST=desafio-mottu-pubsub:8085
      - PUBSUB_PROJECT_ID=desafio-backend-mottu
      - MONGODB_URI=mongodb://user:pass@consumer-db:27017/
    depends_on:
      - desafio-mottu-pubsub
      - consumer-db

  consumer-db:
    image: mongo:8.0
    container_name: DesafioMottu.Consumer.Db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=desafiomottu
    volumes:
      - type: bind
        source: ./.containers/data
        target: /data/db
    ports:
      - 27017:27017